"""add patient_assignment table

Revision ID: 1f3fdda5a25e
Revises: a71a274ae4c5
Create Date: 2026-09-03 09:10:33.158826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3fdda5a25e'
down_revision: Union[str, Sequence[str], None] = 'a71a274ae4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('clinician', 'prosthetist', name='assignment_role'), nullable=False),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_assignments_patient_id'), 'patient_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_practice_id'), 'patient_assignments', ['practice_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_site_id'), 'patient_assignments', ['site_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_user_id'), 'patient_assignments', ['user_id'], unique=False)
    op.create_index('uq_patient_assignments_active', 'patient_assignments', ['patient_id', 'user_id', 'role'], unique=True, postgresql_where=sa.text('end_date IS NULL'), sqlite_where=sa.text('end_date IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_patient_assignments_active', table_name='patient_assignments', postgresql_where=sa.text('end_date IS NULL'), sqlite_where=sa.text('end_date IS NULL'))
    op.drop_index(op.f('ix_patient_assignments_user_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_site_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_practice_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_patient_id'), table_name='patient_assignments')
    op.drop_table('patient_assignments')
    # ### end Alembic commands ###
    # drop_table leaves the enum type behind; remove it so the migration
    # is fully reversible.
    sa.Enum(name='assignment_role').drop(op.get_bind(), checkfirst=True)
