"""add audit_log_entries table

Revision ID: 2dc8f092f86e
Revises: c97a781f4158
Create Date: 2026-09-02 21:15:10.958489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc8f092f86e'
down_revision: Union[str, Sequence[str], None] = 'c97a781f4158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('read', 'create', 'update', 'delete', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_actor_id'), 'audit_log_entries', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entity_id'), 'audit_log_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entity_type'), 'audit_log_entries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_practice_id'), 'audit_log_entries', ['practice_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_timestamp'), 'audit_log_entries', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entries_timestamp'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_practice_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entity_type'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entity_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_actor_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
    # drop_table leaves the enum type behind; remove it so the migration
    # is fully reversible.
    sa.Enum(name='audit_action').drop(op.get_bind(), checkfirst=True)
