"""add prom_record table

Revision ID: 4886871f15e6
Revises: 768352feff3f
Create Date: 2026-09-03 11:21:40.953117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4886871f15e6'
down_revision: Union[str, Sequence[str], None] = '768352feff3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prom_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('instrument', sa.Enum('pain_residual_limb', 'pain_phantom', 'socket_comfort_score', 'locomotor_capabilities_index', name='prom_instrument'), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('flagged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['prosthetic_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prom_records_device_id'), 'prom_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_prom_records_flagged'), 'prom_records', ['flagged'], unique=False)
    op.create_index(op.f('ix_prom_records_instrument'), 'prom_records', ['instrument'], unique=False)
    op.create_index(op.f('ix_prom_records_patient_id'), 'prom_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prom_records_recorded_at'), 'prom_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_prom_records_score'), 'prom_records', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prom_records_score'), table_name='prom_records')
    op.drop_index(op.f('ix_prom_records_recorded_at'), table_name='prom_records')
    op.drop_index(op.f('ix_prom_records_patient_id'), table_name='prom_records')
    op.drop_index(op.f('ix_prom_records_instrument'), table_name='prom_records')
    op.drop_index(op.f('ix_prom_records_flagged'), table_name='prom_records')
    op.drop_index(op.f('ix_prom_records_device_id'), table_name='prom_records')
    op.drop_table('prom_records')
    # ### end Alembic commands ###
    sa.Enum(name='prom_instrument').drop(op.get_bind(), checkfirst=True)
