"""add practice and site tables

Revision ID: 56103820dd12
Revises: 70a342dd741c
Create Date: 2026-09-02 20:51:41.119197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56103820dd12'
down_revision: Union[str, Sequence[str], None] = '70a342dd741c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('hospital_network', 'private_practice', name='practice_type'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('location', 'department', name='site_type'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_practice_id'), 'sites', ['practice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_practice_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('practices')
    # ### end Alembic commands ###
    # create_table auto-creates these enum types but drop_table does not
    # remove them; drop explicitly so the migration is fully reversible.
    sa.Enum(name='site_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='practice_type').drop(op.get_bind(), checkfirst=True)
