"""add recovery_milestone table

Revision ID: 768352feff3f
Revises: 861c2664e43b
Create Date: 2026-09-03 10:50:17.515638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768352feff3f'
down_revision: Union[str, Sequence[str], None] = '861c2664e43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('care_pathway', sa.Enum('lower_limb', 'upper_limb', 'other', name='care_pathway'), nullable=False),
    sa.Column('milestone_type', sa.Enum('pre_prosthetic_assessment', 'cast_socket_fabrication', 'initial_fitting_delivery', 'wear_schedule_desensitization', 'gait_functional_training', 'independent_ambulation_adl', 'community_reintegration_followup', 'prosthetic_use_training', 'myoelectric_training', 'other', name='milestone_type'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'complete', 'delayed', name='milestone_status'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['prosthetic_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_milestones_device_id'), 'recovery_milestones', ['device_id'], unique=False)
    op.create_index(op.f('ix_recovery_milestones_patient_id'), 'recovery_milestones', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_milestones_patient_id'), table_name='recovery_milestones')
    op.drop_index(op.f('ix_recovery_milestones_device_id'), table_name='recovery_milestones')
    op.drop_table('recovery_milestones')
    # ### end Alembic commands ###
    bind = op.get_bind()
    for name in ('milestone_status', 'milestone_type', 'care_pathway'):
        sa.Enum(name=name).drop(bind, checkfirst=True)
