"""add patient table

Revision ID: a71a274ae4c5
Revises: 2dc8f092f86e
Create Date: 2026-09-03 07:16:53.983772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71a274ae4c5'
down_revision: Union[str, Sequence[str], None] = '2dc8f092f86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('passport_number', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('comorbidities', sa.Text(), nullable=True),
    sa.Column('cause_of_limb_loss', sa.Enum('trauma', 'dysvascular', 'infection', 'tumour', 'congenital', 'other', name='cause_of_limb_loss'), nullable=True),
    sa.Column('limb_loss_level', sa.Enum('partial_foot', 'ankle_disarticulation', 'transtibial', 'knee_disarticulation', 'transfemoral', 'hip_disarticulation', 'partial_hand', 'wrist_disarticulation', 'transradial', 'elbow_disarticulation', 'transhumeral', 'shoulder_disarticulation', name='limb_loss_level'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('national_id IS NOT NULL OR passport_number IS NOT NULL', name='ck_patients_identity_present'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_id', 'national_id', name='uq_patients_practice_national_id'),
    sa.UniqueConstraint('practice_id', 'passport_number', name='uq_patients_practice_passport')
    )
    op.create_index(op.f('ix_patients_last_name'), 'patients', ['last_name'], unique=False)
    op.create_index(op.f('ix_patients_practice_id'), 'patients', ['practice_id'], unique=False)
    op.create_index(op.f('ix_patients_site_id'), 'patients', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_site_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_practice_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_last_name'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
    # drop_table leaves the enum types behind; remove them so the
    # migration is fully reversible.
    sa.Enum(name='limb_loss_level').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='cause_of_limb_loss').drop(op.get_bind(), checkfirst=True)
